import type { ModelDefinition } from "../../types";

export const gemini3FlashPreviewModel: ModelDefinition = {
  id: "google/gemini-3-flash-preview",
  displayName: "Gemini 3 Flash",
  callName: "gemini-3-flash-preview",
  description:
    "Intelligent speed-focused model combining frontier performance with search grounding, structured outputs, and long-context support.",
  surfaces: ["chat", "extraction"],
  limits: {
    maxContextTokens: 1048576,
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
  },
  capabilities: {
    multimodalInput: true,
    searchGrounding: true,
    mediaResolution: true,
    safetySettings: true,
    stopSequences: true,
    googleMapsGrounding: true,
    urlContext: true,
    codeExecution: true,
    fileSearch: true,
    structuredOutputs: true,
    functionCalling: true,
    thinking: true,
  },
  settings: [
    { settingId: "temperature" },
    { settingId: "topP" },
    { settingId: "topK" },
    { settingId: "maxInputTokens", defaultValue: 1048576, max: 1048576 },
    { settingId: "maxContextTokens", defaultValue: 1048576, max: 1048576 },
    { settingId: "maxOutputTokens", defaultValue: 8192, max: 65536 },
    { settingId: "enableSearch" },
    { settingId: "googleMapsGrounding" },
    { settingId: "urlContext" },
    { settingId: "codeExecution" },
    { settingId: "fileSearch" },
    { settingId: "harassmentSafety" },
    { settingId: "hateSpeechSafety" },
    { settingId: "sexuallyExplicitSafety" },
    { settingId: "dangerousContentSafety" },
    {
      settingId: "thinkingLevel",
      defaultValue: "high",
      options: [
        { value: "minimal", label: "Minimal" },
        { value: "low", label: "Low" },
        { value: "medium", label: "Medium" },
        { value: "high", label: "High" },
      ],
    },
    { settingId: "responseMimeType" },
    { settingId: "responseSchemaJson" },
    { settingId: "functionDeclarationsJson" },
    { settingId: "mediaResolution" },
    { settingId: "stopSequences" },
  ],
};
