import type { ModelDefinition } from "../../types";

export const gemini31FlashLitePreviewModel: ModelDefinition = {
  id: "google/gemini-3.1-flash-lite-preview",
  displayName: "Gemini 3.1 Flash-Lite",
  callName: "gemini-3.1-flash-lite-preview",
  description:
    "Cost-efficient model optimized for high-volume agentic tasks, translation, and simple data processing with multimodal support.",
  surfaces: ["chat", "extraction"],
  limits: {
    maxContextTokens: 1048576,
    maxInputTokens: 1048576,
    maxOutputTokens: 65536,
  },
  capabilities: {
    multimodalInput: true,
    searchGrounding: true,
    mediaResolution: true,
    safetySettings: true,
    stopSequences: true,
    googleMapsGrounding: true,
    urlContext: true,
    codeExecution: true,
    fileSearch: true,
    structuredOutputs: true,
    functionCalling: true,
    thinking: true,
  },
  settings: [
    { settingId: "temperature" },
    { settingId: "topP" },
    { settingId: "topK" },
    { settingId: "maxInputTokens" },
    { settingId: "maxOutputTokens", defaultValue: 65536, max: 65536 },
    { settingId: "enableSearch" },
    { settingId: "urlContext" },
    { settingId: "codeExecution" },
    { settingId: "harassmentSafety" },
    { settingId: "hateSpeechSafety" },
    { settingId: "sexuallyExplicitSafety" },
    { settingId: "dangerousContentSafety" },
    { settingId: "thinkingLevel", defaultValue: "high" },
    { settingId: "mediaResolution" },
  ],
};
