import type { SettingDefinition } from "./types";

export const settingCatalog: Record<string, SettingDefinition> = {
  temperature: {
    id: "temperature",
    displayName: "Temperature",
    description: "Controls how deterministic or creative the output should be.",
    valueType: "number",
    control: "slider",
    defaultValue: 1,
    min: 0,
    max: 2,
    step: 0.1,
  },
  topP: {
    id: "topP",
    displayName: "Top P",
    description: "Limits token selection to the smallest high-probability set.",
    valueType: "number",
    control: "slider",
    defaultValue: 0.95,
    min: 0,
    max: 1,
    step: 0.01,
  },
  topK: {
    id: "topK",
    displayName: "Top K",
    description: "Limits token selection to the K most likely candidates.",
    valueType: "number",
    control: "slider",
    defaultValue: 0,
    min: 0,
    max: 1000,
    step: 1,
  },
  maxOutputTokens: {
    id: "maxOutputTokens",
    displayName: "Max Output Tokens",
    description: "Caps how many tokens the model may generate in one response.",
    valueType: "number",
    control: "input",
    defaultValue: 65536,
    min: 1,
    max: 262144,
    step: 1,
    unit: "tokens",
  },
  maxInputTokens: {
    id: "maxInputTokens",
    displayName: "Max Input Tokens",
    description: "Caps how many input tokens can be sent in one request.",
    valueType: "number",
    control: "input",
    defaultValue: 8192,
    min: 1,
    max: 2097152,
    step: 1,
    unit: "tokens",
  },
  maxContextTokens: {
    id: "maxContextTokens",
    displayName: "Max Context Tokens",
    description: "Caps the total context window used for a model interaction.",
    valueType: "number",
    control: "input",
    defaultValue: 8192,
    min: 1,
    max: 2097152,
    step: 1,
    unit: "tokens",
  },
  enableSearch: {
    id: "enableSearch",
    displayName: "Enable Search",
    description: "Lets the provider attach its search tool to the request.",
    valueType: "boolean",
    control: "toggle",
    defaultValue: false,
  },
  codeExecution: {
    id: "codeExecution",
    displayName: "Code Execution",
    description: "Lets the model use the built-in code execution tool.",
    valueType: "boolean",
    control: "toggle",
    defaultValue: false,
  },
  fileSearch: {
    id: "fileSearch",
    displayName: "File Search",
    description: "Lets the model search indexed files and documents.",
    valueType: "boolean",
    control: "toggle",
    defaultValue: false,
  },
  stopSequences: {
    id: "stopSequences",
    displayName: "Stop Sequences",
    description: "Stop strings that end generation when matched.",
    valueType: "string",
    control: "textarea",
    defaultValue: "",
  },
  thinkingLevel: {
    id: "thinkingLevel",
    displayName: "Thinking Level",
    description: "Controls whether and how strongly the model uses its reasoning pass.",
    valueType: "enum",
    control: "select",
    defaultValue: "high",
    options: [
      { value: "off", label: "Off" },
      { value: "minimal", label: "Minimal" },
      { value: "low", label: "Low" },
      { value: "medium", label: "Medium" },
      { value: "high", label: "High" },
    ],
  },
  thinkingBudget: {
    id: "thinkingBudget",
    displayName: "Thinking Budget",
    description: "Sets a numeric budget for reasoning tokens when a model supports it.",
    valueType: "number",
    control: "input",
    defaultValue: 8192,
    min: 0,
    max: 32768,
    step: 1,
    unit: "tokens",
  },
  responseSchemaJson: {
    id: "responseSchemaJson",
    displayName: "Response Schema JSON",
    description: "JSON Schema to use when structured outputs are enabled.",
    valueType: "string",
    control: "textarea",
    defaultValue: "",
  },
  functionDeclarationsJson: {
    id: "functionDeclarationsJson",
    displayName: "Function Declarations JSON",
    description: "JSON array describing tools and callable functions.",
    valueType: "string",
    control: "textarea",
    defaultValue: "[]",
  },
  outputDimensionality: {
    id: "outputDimensionality",
    displayName: "Output Dimensionality",
    description: "Controls the final size of the returned embedding vector.",
    valueType: "number",
    control: "select",
    defaultValue: 768,
    min: 128,
    max: 32768,
    step: 128,
  },
};

export function getSettingDefinition(settingId: string): SettingDefinition | undefined {
  return settingCatalog[settingId];
}
